FROM debian:buster-slim
COPY custom_jre/ /opt/java/custom_jre/
COPY target/*.jar /app/app.jar

WORKDIR /app
ENV JAVA_HOME=/opt/java/custom_jre
ENV PATH=$JAVA_HOME/bin:$PATH

EXPOSE 8080
ENTRYPOINT ["/opt/java/custom_jre/bin/java","-jar","/app/app.jar"]


