name: Build and publish to GitHub Container Registry

on:
  push:
    branches: [ main, master ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 24
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '24'

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build with Maven
        run: mvn -B -DskipTests package

      - name: List target directory for debugging
        run: |
          echo "PWD=$(pwd)"
          ls -la
          echo "--- target listing ---"
          if [ -d target ]; then ls -la target; else echo "target directory does not exist"; fi

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image to GHCR
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          load: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:${{ github.sha }}
            ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:latest

      - name: Show pushed image size
        run: |
          IMAGE=ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:${{ github.sha }}
          echo "Inspecting $IMAGE"
          echo "-- local docker images --"
          docker images --format 'table {{.Repository}}:{{.Tag}}	{{.Size}}'
          echo "-- attempting inspect --"
          SIZE_BYTES=$(docker image inspect "$IMAGE" --format '{{.Size}}' 2>/dev/null || true)
          if [ -n "$SIZE_BYTES" ]; then
            echo "Size bytes: $SIZE_BYTES"
            if command -v numfmt >/dev/null 2>&1; then
              echo "Human: $(numfmt --to=iec-i --suffix=B $SIZE_BYTES)"
            fi
          else
            echo "Image not found locally; attempting remote manifest size via registry"
            TOKEN="$GITHUB_TOKEN"
            # Try manifest API (may require additional scopes for private packages)
            curl -s -u ${{ github.actor }}:$TOKEN -H "Accept: application/vnd.docker.distribution.manifest.v2+json" \
              "https://ghcr.io/v2/${{ github.repository_owner }}/${{ github.event.repository.name }}/manifests/${{ github.sha }}" \
              | jq '.layers | map(.size) | add' >/tmp/manifest_size 2>/dev/null || true
            if [ -s /tmp/manifest_size ]; then
              MANIFEST_BYTES=$(cat /tmp/manifest_size)
              echo "Remote manifest total bytes: $MANIFEST_BYTES"
              if command -v numfmt >/dev/null 2>&1; then
                echo "Human: $(numfmt --to=iec-i --suffix=B $MANIFEST_BYTES)"
              fi
            else
              echo "Could not determine remote image size."
            fi
          fi

      - name: Output image tag
        run: echo "IMAGE=ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:${{ github.sha }}" >> $GITHUB_OUTPUT


